[package]
name = "struct-metadata"
version = "0.1.0"
edition = "2021"
licence = "MIT"
categories = ["rust-patterns", "config"]
description = "Macros for attaching metadata to structs."


[dependencies]
struct-metadata-derive = { version = "0", path = "../struct-metadata-derive" }
chrono = { version = "0.4", optional = true }

[features]
default = ["std", "chrono"]
std = []
chrono = ["dep:chrono"]

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.25", features = ["derive"] }
