[package]
name = "struct-metadata"
version = "0.1.0"
edition = "2021"
categories = ["rust-patterns", "config"]
description = "Macros for attaching metadata to structs."


[dependencies]
struct-metadata-derive = { version = "0", path = "../struct-metadata-derive" }
