[package]
name = "struct-metadata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
struct-metadata-derive = { version = "0", path = "../struct-metadata-derive" }
